# Generated by Django 5.0.1 on 2025-04-03 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appoint_area',
            field=models.CharField(choices=[('', '----------'), ('Dentistry', 'Dentistry'), ('Pharmacy', 'Pharmacy'), ('Consultation', 'Consultation'), ('Flu Treatment', 'Flu Treatment'), ('ENT', 'Ear, Nose, and Throat (ENT)'), ('Mental Health', 'Mental Health'), ('Physiotherapy', 'Physiotherapy'), ('Reproductive Health', 'Reproductive Health'), ('Covid-Screening', 'Covid-19 Screening'), ('VCT', 'HIV Counselling & Treatment'), ('Laboratory', 'Laboratory Tests'), ('Referral', 'Referral'), ('Other issue', 'Other issue')], max_length=19, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='id',
            name='patient_type',
            field=models.CharField(choices=[('', '-----'), ('Student', 'Youth'), ('Staff', 'Adult')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='patient_type',
            field=models.CharField(choices=[('', '-----'), ('Student', 'Youth'), ('Staff', 'Adult')], max_length=50),
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Prescription Details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='account.appointment')),
                ('prescribed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
