# Generated by Django 5.0.1 on 2025-04-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_appointment_appoint_area_alter_id_patient_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
