# Generated by Django 5.0.1 on 2025-04-03 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_prescription_prescribed_for_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='prescribed_for_patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_prescriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
